version: '2'
services:

  # TODO: development

  # test
  test:
    build: .
    tty: true
    depends_on:
      - test_db
      - test_redis
    environment:
      - REDIS_HOST=test_redis
      - REDIS_PASSWORD=db62b65a8d19a213
      - DATABASE_HOST=test_db
      - RAILS_ENV=test
    volumes:
      - $PWD:/usr/src/app
    command: rake rails_app:install rails_app:db spec
  test_db:
    image: mysql:5.6
    expose:
      - "3306"
    volumes:
      - ~/.docker-volumes/bigbluebutton_rails/test/mysql/:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=mconf
      - MYSQL_DATABASE=bigbluebutton_rails_test
      - MYSQL_USER=mconf
      - MYSQL_PASSWORD=mconf
  test_redis:
    image: redis:3.2
    expose:
      - "6379"
    command: redis-server --requirepass "db62b65a8d19a213"
