finish_meetings:
  every:
    - "5m"
  class: BigbluebuttonFinishMeetings
  description: "Checks for meetings that finished and mark as finished. Same as 'rake bigbluebutton_rails:meetings:finish'."

get_stats:
  every:
    - "2m"
  class: BigbluebuttonGetStats
  description: "Checks for meeting's stats. Currently works on Mconf-Live servers and will get a list of participants and meeting duration."

update_recordings:
  every:
    - "30m"
  class: BigbluebuttonUpdateRecordings
  description: "Gets the recordings in the server to populate the db. Same as 'rake bigbluebutton_rails:recordings:update'."

update_server_configs:
  every:
    - "1h"
  class: BigbluebuttonUpdateServerConfigs
  description: "Updates the server configs that are stored locally. Same as 'rake bigbluebutton_rails:server_configs:update'."
